### ISSUE TITLE
Create separate repo for k8s deployment files

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha-Rules-Decision#41]
@krook the k8s deployment files are currently under `https://github.com/Pyrrha-Platform/Pyrrha-Rules-Decision/tree/master/chart/rulesdecision`. We should move all deployment files outside code. I suggest creating `Pyrrha-Deployment` repository. I would like to move all deployment artifacts to this new repository. The existing repositories will host the code and Dockerfile to create the containers. Deployment can happen on IKS, OpenShift or Code Engine.

**Comment by krook** [comment]
I believe this is now done.

**Comment by krook** [comment]
Done: https://github.com/Pyrrha-Platform/Pyrrha-Deployment-Configurations
