### ISSUE TITLE
Docker image exiting after docker run

### ISSUE THREAD

**Issue by Aquijada52** [Pyrrha-Platform/Pyrrha-Rules-Decision#47]

**Comment by Aquijada52** [comment]
When executing command `docker run -p 3306:3306 --name pyrrha-mariadb -e MYSQL_ROOT_PASSWORD='' -d mariadb`, I use the command `docker ps -a`, and the image almost immediately exits. 


![Screen Shot 2021-07-27 at 9 01 36 AM](https://user-images.githubusercontent.com/84873806/127187645-a6a91471-c70e-47cf-a4b7-233a474713e2.png)

<img width="886" alt="Screen Shot 2021-07-27 at 9 03 56 AM" src="https://user-images.githubusercontent.com/84873806/127187996-35aa3770-9b0a-4eb4-8837-0d2e7e895c56.png">

**Comment by dacamposol** [comment]
@upkarlidder I think this can be closed as well
